### ISSUE TITLE
Plans to update this to 1.20.X?

### ISSUE THREAD

**Issue by PlayfulPiano** [dhyces/InventoryTabs#5]
Was wondering if this mod still has plans for updating to the latest version of minecraft. Hopefully includes 1.20.1 as I believe a lot of mods are mostly available for that version over 1.20.2.

**Comment by dhyces** [comment]
Just responded to a similar comment on the project page. I'm busy with finals at the moment, but I will look into getting it updated in the near future.

**Comment by PlayfulPiano** [comment]
Thank you!

**Comment by dhyces** [comment]
The update to 1.20.1 is now released, with thanks to ALFEECLARE for the update PR. Thank you for your patience!
